-- MySQL Script generated by MySQL Workbench
-- Fri 30 Nov 2018 03:55:21 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema li-bot-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `li-bot-db` ;

-- -----------------------------------------------------
-- Schema li-bot-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `li-bot-db` ;
USE `li-bot-db` ;

-- -----------------------------------------------------
-- Table `li-bot-db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `li-bot-db`.`user` ;

CREATE TABLE IF NOT EXISTS `li-bot-db`.`user` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NULL,
  `money` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
